<HashingScreen>:
    FloatLayout:
        pos_hint: {"y": 0}
        size_hint: 1, 1

        Button:
            pos_hint: {"x": 0,"y": 0.7999}
            size_hint: 0.4, 0.2

            text: "Start Mining"
            font_size: text_font_size

        Label:

        canvas:
            Color:
                rgb: 1, 0, 0
        pos_hint: {"x": 0.5,"y": 0}
        size_hint: 0.5, 0.8
        text: "log_go_here_lol"
        font_size: text_font_size






