<HashingScreen>:
    FloatLayout:
        pos_hint: {"y": 0}
        size_hint: 1, 1

        Button:
            pos_hint: {"x": 0,"y": 0.7999}
            size_hint: 0.4, 0.2

            text: "Start Mining"
            font_size: text_font_size

        Button:
            pos_hint: {"x": 0.6,"y": 0.9}
            size_hint: 0.4, 0.1

            text: "Logs"
            font_size: text_font_size