<Header@BoxLayout>:
    orientation: "horizontal"

    ToggleButton:
        text: "Home"
        group: "Header"
        state: "down"

    ToggleButton:
        text: "Hashing"
        group: "Header"

<HomeScreen>:
    Header:
        pos_hint: {"top": 1}
        size_hint: 1, 0.1

<HashingScreen>:
    Header:
        pos_hint: {"top": 1}
        size_hint: 1, 0.1

<ScreenManager>:
    HomeScreen:
        name: "HomeScreen"

    HashingScreen:
        name: "HashingScreen"
